INFO 2022-07-02 17:45:04 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
ERROR 2022-07-02 17:45:04 BaseModelLoader.py: 33] The configuration file meta.json was not found or failed to parse the file!
INFO 2022-07-02 17:48:55 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 17:48:55 BaseModelLoader.py: 39] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 17:48:55 FaceDetModelLoader.py: 34] The model failed to load, please check the model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 17:54:08 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 17:54:08 BaseModelLoader.py: 39] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 17:54:08 FaceDetModelLoader.py: 34] The model failed to load, please check the model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 17:57:00 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 17:57:00 BaseModelLoader.py: 39] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 17:57:00 FaceDetModelLoader.py: 35] The model failed to load, please check the model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 18:08:40 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
ERROR 2022-07-02 18:08:40 BaseModelLoader.py: 33] The configuration file meta.json was not found or failed to parse the file!
INFO 2022-07-02 18:09:48 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
ERROR 2022-07-02 18:09:48 BaseModelLoader.py: 34] The configuration file meta.json was not found or failed to parse the file!
INFO 2022-07-02 18:10:52 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
ERROR 2022-07-02 18:10:52 BaseModelLoader.py: 34] The configuration file meta.json was not found or failed to parse the file!
INFO 2022-07-02 18:12:14 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 18:12:14 BaseModelLoader.py: 40] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 18:12:14 FaceDetModelLoader.py: 34] The model failed to load, please check the model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 18:15:17 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 18:15:17 BaseModelLoader.py: 40] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 18:15:17 FaceDetModelLoader.py: 35] The model failed to load, please check the model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 18:15:47 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 18:15:47 BaseModelLoader.py: 40] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 18:15:47 FaceDetModelLoader.py: 35] The model failed to load, please check the model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 18:15:54 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 18:15:54 BaseModelLoader.py: 40] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 18:15:54 FaceDetModelLoader.py: 35] The model failed to load, please check the model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 18:16:18 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 18:16:18 BaseModelLoader.py: 40] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 18:16:18 FaceDetModelLoader.py: 35] The model failed to load, please check the model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 21:50:23 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 21:50:23 BaseModelLoader.py: 39] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 21:50:23 FaceDetModelLoader.py: 34] The model failed to load, please check the model path: /Users/vega/workspace/codes/py_space/working/photo-tools-api/core/extensions/face_detect/face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 21:52:11 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
ERROR 2022-07-02 21:52:11 BaseModelLoader.py: 33] The configuration file meta.json was not found or failed to parse the file!
INFO 2022-07-02 21:53:50 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
ERROR 2022-07-02 21:53:50 BaseModelLoader.py: 34] The configuration file meta.json was not found or failed to parse the file!
INFO 2022-07-02 21:54:32 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 21:54:32 BaseModelLoader.py: 40] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 21:54:32 FaceDetModelLoader.py: 34] The model failed to load, please check the model path: models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 21:54:40 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 21:54:40 BaseModelLoader.py: 40] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 21:54:40 FaceDetModelLoader.py: 34] The model failed to load, please check the model path: models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 21:56:39 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 21:56:39 BaseModelLoader.py: 40] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 21:56:39 FaceDetModelLoader.py: 35] The model failed to load, please check the model path: models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 21:57:22 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 21:57:22 BaseModelLoader.py: 40] Successfully parsed the model configuration file meta.json!
ERROR 2022-07-02 21:57:22 FaceDetModelLoader.py: 35] The model failed to load, please check the model path: models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2022-07-02 22:04:15 FaceDetModelLoader.py: 20] Start to analyze the face detection model, model path: models, model category: face_detection，model name: face_detection_1.0
INFO 2022-07-02 22:04:15 BaseModelLoader.py: 39] Successfully parsed the model configuration file meta.json!
